version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: demo-test
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          profile-name:
          region: AWS_DEFAULT_REGION
          repo: AWS_ECR_URL
          skip-when-tags-exist: false
          tag: 'latest,ocj_test'
